// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmyyvuerjtxeolkwpnrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJteXl2dWVyanR4ZW9sa3dwbnJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNzcyODgsImV4cCI6MjA3MTg1MzI4OH0.mXYr0J3Zg_junhl34834VOokr4sLkU9jI9qf8dXC2SI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});